package frm;

import DTOs.Chat;
import DTOs.Mensaje;
import DTOs.Usuario;
import control.ControlChat;
import control.ControlMensaje;
import control.ControlUsuario;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author eduar
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private Usuario usuario;
    private ControlChat controlChat;
    private ControlMensaje controlMensaje;
    private ControlUsuario controlUsuario;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal(Usuario usuario) {
        this.usuario = usuario;
        this.controlChat = new ControlChat();
        this.controlMensaje = new ControlMensaje();
        this.controlUsuario = new ControlUsuario();
        initComponents();
        cargarChats();
    }

    private void cargarChats() {
        DefaultListModel<String> model = new DefaultListModel<>();
        List<Chat> chats = controlChat.obtenerChatsUsuario(usuario.getTelefono());
        for (Chat chat : chats) {
            model.addElement(chat.getNombreChat());
        }
        listaChats.setModel(model);
    }

    private void cargarMensajes(Chat chat) {
        DefaultListModel<String> model = new DefaultListModel<>();
        List<Mensaje> mensajes = controlMensaje.obtenerMensajesChat(chat.getId());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        for (Mensaje mensaje : mensajes) {
            Usuario remitente = controlUsuario.obtenerUsuarioPorId(mensaje.getUsuarioId());
            String remitenteNombre = remitente != null ? remitente.getNombre() : "Desconocido";
            String fechaHora = mensaje.getFechaHora() != null ? sdf.format(mensaje.getFechaHora()) : "Fecha desconocida";
            String texto = String.format("%s [%s]: %s", remitenteNombre, fechaHora, mensaje.getTextoMensaje());
            model.addElement(texto);
        }
        listaMensajes.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JTextField();
        botonEnviar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMensajes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaChats = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPerfil = new javax.swing.JMenu();
        menuModificarPerfil = new javax.swing.JMenuItem();
        menuCrearChat = new javax.swing.JMenu();
        menuCerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Chats");

        botonEnviar.setText("Enviar");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaMensajes);

        listaChats.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaChatsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaChats);

        menuPerfil.setText("Perfil");

        menuModificarPerfil.setText("Modificar Perfil");
        menuModificarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModificarPerfilActionPerformed(evt);
            }
        });
        menuPerfil.add(menuModificarPerfil);

        jMenuBar1.add(menuPerfil);

        menuCrearChat.setText("Crear Chat");
        menuCrearChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCrearChatMouseClicked(evt);
            }
        });
        menuCrearChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearChatActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuCrearChat);

        menuCerrarSesion.setText("Cerrar Sesión");
        menuCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCerrarSesionMouseClicked(evt);
            }
        });
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuCerrarSesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(153, 153, 153))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEnviar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
        InicioSesion inicioSesion = new InicioSesion();
        inicioSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    private void menuCrearChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearChatActionPerformed
        PantallaCrearChat pantallaCrearChat = new PantallaCrearChat(usuario);
        pantallaCrearChat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuCrearChatActionPerformed

    private void menuModificarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModificarPerfilActionPerformed
        PantallaPerfil pantallaPerfil = new PantallaPerfil(usuario);
        pantallaPerfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuModificarPerfilActionPerformed

    private void listaChatsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaChatsValueChanged
        if (!evt.getValueIsAdjusting()) {
            String chatNombre = listaChats.getSelectedValue();
            if (chatNombre != null) {
                Chat chat = controlChat.buscarChatPorNombre(chatNombre);
                if (chat != null) {
                    cargarMensajes(chat);
                }
            }
        }
    }//GEN-LAST:event_listaChatsValueChanged

    private void menuCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCerrarSesionMouseClicked
        InicioSesion inicioSesion = new InicioSesion();
        inicioSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuCerrarSesionMouseClicked

    private void menuCrearChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCrearChatMouseClicked
        PantallaCrearChat pantallaCrearChat = new PantallaCrearChat(usuario);
        pantallaCrearChat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuCrearChatMouseClicked

    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        String mensajeTexto = txtMensaje.getText().trim();
        if (mensajeTexto.isEmpty()) {
            return;
        }

        String chatNombre = listaChats.getSelectedValue();
        if (chatNombre == null) {
            JOptionPane.showMessageDialog(this, "Selecciona un chat primero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Chat chat = controlChat.buscarChatPorNombre(chatNombre);
        if (chat == null) {
            JOptionPane.showMessageDialog(this, "Chat no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        controlMensaje.enviarMensaje(chat.getId(), usuario.getId(), mensajeTexto, null);
        txtMensaje.setText("");
        cargarMensajes(chat);
    }//GEN-LAST:event_botonEnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaChats;
    private javax.swing.JList<String> listaMensajes;
    private javax.swing.JMenu menuCerrarSesion;
    private javax.swing.JMenu menuCrearChat;
    private javax.swing.JMenuItem menuModificarPerfil;
    private javax.swing.JMenu menuPerfil;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables

}
